# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - main
    - 'ci/**'

jobs:
  build-maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw clean package verify

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  build-docker:

    runs-on: ubuntu-latest
    needs: build-maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v4
      with:
        name: java-app

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build the Docker image
      run: docker build . -t ghcr.io/seniorroland/cubix/1/optional/app:springboot
    - name: Publishing the Docker image
      run: docker push ghcr.io/seniorroland/cubix/1/optional/app:springboot

    
